name: 11ty GH Pages Action
  # You may pin to the exact commit or the version.
  # uses: cjerrington/actions-eleventy@3c1bab6d316d9fa9f13e71464b578910f9ddb678
  uses: cjerrington/actions-eleventy@v1.0
  with:
    # Arguments to pass to the Eleventy invocation
    args: # optional
    # If set to `true`, `npm install` will be run before Eleventy is invoked
    install_dependencies: # optional
